import Silean.Modules.BitMux
import Silean.Modules.Constant
import Silean.Modules.All
import Silean.Modules.HalfAdder
import Silean.Modules.Increment
import Silean.Modules.Register
import Silean.Modules.ResetRegister
import Silean.Modules.EnabledResetRegister
import Silean.Modules.EnabledResetCounter
import Silean.Modules.Fifo.Fifo
import Silean.Modules.Fifo.FifoProperties
import Silean.Modules.Fifo.FifoCertified
import Silean.Modules.Mask
import Silean.Modules.BitwiseOr
import Silean.Modules.BinaryToOneHot
import Silean.Modules.CombMuxTree
import Silean.Modules.RegisterBank
import Silean.Modules.Mux
import Silean.Modules.EnabledRegister
import Silean.Modules.Equality
import Silean.Modules.OneEntryFifo.OneEntryFifo
import Silean.Modules.OneEntryFifo.OneEntryFifoCycleBehavior
import Silean.Modules.VectorConcat
import Silean.Modules.VectorSplit
import Silean.Modules.SerialDepthFifo.SerialDepthFifo
import Silean.Modules.OneEntryFifo.OneEntryFifoCertified
import Silean.Modules.SerialDepthFifo.SerialDepthFifoCertified
